name: Deploy to Heroku

on:
  push:
    branches:
      - main # Sadece main branch’e push yapıldığında çalışır.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Repository'yi çek
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Heroku'ya deploy et
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
